//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
    providedIn: 'root'
})
export class UserContextClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getAccessibleEstablishments(): Observable<string[]> {
        let url_ = this.baseUrl + "/api/user-context/get-accessible-establishments";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAccessibleEstablishments(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAccessibleEstablishments(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<string[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<string[]>;
        }));
    }

    protected processGetAccessibleEstablishments(response: HttpResponseBase): Observable<string[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class AnalysisClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    correlationCoefficientAndLag(command: CorrelationCommand): Observable<CorrelationReturn> {
        let url_ = this.baseUrl + "/api/analysis/cross-correlation-with-weather";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCorrelationCoefficientAndLag(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCorrelationCoefficientAndLag(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CorrelationReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CorrelationReturn>;
        }));
    }

    protected processCorrelationCoefficientAndLag(response: HttpResponseBase): Observable<CorrelationReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CorrelationReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    timeOfVisitTotalPrice(command: ClusteringCommand): Observable<ClusteringReturn> {
        let url_ = this.baseUrl + "/api/analysis/Clustering";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTimeOfVisitTotalPrice(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTimeOfVisitTotalPrice(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<ClusteringReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<ClusteringReturn>;
        }));
    }

    protected processTimeOfVisitTotalPrice(response: HttpResponseBase): Observable<ClusteringReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ClusteringReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class AuthenticationClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    logIn(loginCommand: LoginCommand): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/authentication/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(loginCommand);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLogIn(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLogIn(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processLogIn(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    isLoggedIn(): Observable<boolean> {
        let url_ = this.baseUrl + "/api/authentication/is-logged-in";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processIsLoggedIn(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processIsLoggedIn(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<boolean>;
                }
            } else
                return _observableThrow(response_) as any as Observable<boolean>;
        }));
    }

    protected processIsLoggedIn(response: HttpResponseBase): Observable<boolean> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    logOut(): Observable<FileResponse> {
        let url_ = this.baseUrl + "/api/authentication/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Accept": "application/octet-stream"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processLogOut(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processLogOut(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<FileResponse>;
                }
            } else
                return _observableThrow(response_) as any as Observable<FileResponse>;
        }));
    }

    protected processLogOut(response: HttpResponseBase): Observable<FileResponse> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return _observableOf({ fileName: fileName, data: responseBlob as any, status: status, headers: _headers });
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class DataSeedClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    seedDatabase(): Observable<void> {
        let url_ = this.baseUrl + "/api/test";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSeedDatabase(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSeedDatabase(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processSeedDatabase(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class EstablishmentClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getEstablishmentdID(command: GetEstablishmentsCommand): Observable<GetEstablishmentsIdReturn> {
        let url_ = this.baseUrl + "/api/establishment/get-id";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetEstablishmentdID(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetEstablishmentdID(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetEstablishmentsIdReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetEstablishmentsIdReturn>;
        }));
    }

    protected processGetEstablishmentdID(response: HttpResponseBase): Observable<GetEstablishmentsIdReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetEstablishmentsIdReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getEstablishmentsDTO(command: GetEstablishmentsCommand): Observable<GetEstablishmentsDTOReturn> {
        let url_ = this.baseUrl + "/api/establishment/get-DTO";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetEstablishmentsDTO(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetEstablishmentsDTO(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetEstablishmentsDTOReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetEstablishmentsDTOReturn>;
        }));
    }

    protected processGetEstablishmentsDTO(response: HttpResponseBase): Observable<GetEstablishmentsDTOReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetEstablishmentsDTOReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class ItemClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getItems(command: GetItemsCommand): Observable<GetItemsIdReturn> {
        let url_ = this.baseUrl + "/api/establishment/item/get";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetItems(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetItems(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetItemsIdReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetItemsIdReturn>;
        }));
    }

    protected processGetItems(response: HttpResponseBase): Observable<GetItemsIdReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetItemsIdReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    getItemsDTO(command: GetItemsCommand): Observable<GetItemsDTOReturn> {
        let url_ = this.baseUrl + "/api/establishment/item/get-DTO";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetItemsDTO(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetItemsDTO(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetItemsDTOReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetItemsDTOReturn>;
        }));
    }

    protected processGetItemsDTO(response: HttpResponseBase): Observable<GetItemsDTOReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetItemsDTOReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

@Injectable({
    providedIn: 'root'
})
export class SaleClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    getSales(command: GetSalesCommand): Observable<GetSalesReturn> {
        let url_ = this.baseUrl + "/api/establishment/sales/find-sales";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(command);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            withCredentials: true,
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetSales(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetSales(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<GetSalesReturn>;
                }
            } else
                return _observableThrow(response_) as any as Observable<GetSalesReturn>;
        }));
    }

    protected processGetSales(response: HttpResponseBase): Observable<GetSalesReturn> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetSalesReturn.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

export abstract class ReturnBase implements IReturnBase {

    constructor(data?: IReturnBase) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): ReturnBase {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'ReturnBase' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface IReturnBase {
}

export class CorrelationReturn extends ReturnBase implements ICorrelationReturn {
    lagAndCorrelation!: ValueTupleOfIntegerAndDouble[];
    calculationValues!: ValueTupleOfDateTimeAndListOfNullableDouble[];

    constructor(data?: ICorrelationReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["lagAndCorrelation"])) {
                this.lagAndCorrelation = [] as any;
                for (let item of _data["lagAndCorrelation"])
                    this.lagAndCorrelation!.push(ValueTupleOfIntegerAndDouble.fromJS(item));
            }
            if (Array.isArray(_data["calculationValues"])) {
                this.calculationValues = [] as any;
                for (let item of _data["calculationValues"])
                    this.calculationValues!.push(ValueTupleOfDateTimeAndListOfNullableDouble.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): CorrelationReturn {
        data = typeof data === 'object' ? data : {};
        let result = new CorrelationReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.lagAndCorrelation)) {
            data["lagAndCorrelation"] = [];
            for (let item of this.lagAndCorrelation)
                data["lagAndCorrelation"].push(item.toJSON());
        }
        if (Array.isArray(this.calculationValues)) {
            data["calculationValues"] = [];
            for (let item of this.calculationValues)
                data["calculationValues"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface ICorrelationReturn extends IReturnBase {
    lagAndCorrelation: ValueTupleOfIntegerAndDouble[];
    calculationValues: ValueTupleOfDateTimeAndListOfNullableDouble[];
}

export class ValueTupleOfIntegerAndDouble implements IValueTupleOfIntegerAndDouble {
    item1!: number;
    item2!: number;

    constructor(data?: IValueTupleOfIntegerAndDouble) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item1 = _data["item1"];
            this.item2 = _data["item2"];
        }
    }

    static fromJS(data: any): ValueTupleOfIntegerAndDouble {
        data = typeof data === 'object' ? data : {};
        let result = new ValueTupleOfIntegerAndDouble();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item1"] = this.item1;
        data["item2"] = this.item2;
        return data;
    }
}

export interface IValueTupleOfIntegerAndDouble {
    item1: number;
    item2: number;
}

export class ValueTupleOfDateTimeAndListOfNullableDouble implements IValueTupleOfDateTimeAndListOfNullableDouble {
    item1!: Date;
    item2!: (number | undefined)[] | undefined;

    constructor(data?: IValueTupleOfDateTimeAndListOfNullableDouble) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item1 = _data["item1"] ? new Date(_data["item1"].toString()) : <any>undefined;
            if (Array.isArray(_data["item2"])) {
                this.item2 = [] as any;
                for (let item of _data["item2"])
                    this.item2!.push(item);
            }
        }
    }

    static fromJS(data: any): ValueTupleOfDateTimeAndListOfNullableDouble {
        data = typeof data === 'object' ? data : {};
        let result = new ValueTupleOfDateTimeAndListOfNullableDouble();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item1"] = this.item1 ? this.item1.toISOString() : <any>undefined;
        if (Array.isArray(this.item2)) {
            data["item2"] = [];
            for (let item of this.item2)
                data["item2"].push(item);
        }
        return data;
    }
}

export interface IValueTupleOfDateTimeAndListOfNullableDouble {
    item1: Date;
    item2: (number | undefined)[] | undefined;
}

export abstract class CommandBase implements ICommandBase {

    constructor(data?: ICommandBase) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
    }

    static fromJS(data: any): CommandBase {
        data = typeof data === 'object' ? data : {};
        throw new Error("The abstract class 'CommandBase' cannot be instantiated.");
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        return data;
    }
}

export interface ICommandBase {
}

export class CorrelationCommand extends CommandBase implements ICorrelationCommand {
    establishmentId!: string;
    salesIds!: string[];
    timePeriod!: DateTimePeriod;
    timeResolution!: TimeResolution;
    upperLag!: number;
    lowerLag!: number;

    constructor(data?: ICorrelationCommand) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.establishmentId = _data["establishmentId"];
            if (Array.isArray(_data["salesIds"])) {
                this.salesIds = [] as any;
                for (let item of _data["salesIds"])
                    this.salesIds!.push(item);
            }
            this.timePeriod = _data["timePeriod"] ? DateTimePeriod.fromJS(_data["timePeriod"]) : <any>undefined;
            this.timeResolution = _data["timeResolution"];
            this.upperLag = _data["upperLag"];
            this.lowerLag = _data["lowerLag"];
        }
    }

    static override fromJS(data: any): CorrelationCommand {
        data = typeof data === 'object' ? data : {};
        let result = new CorrelationCommand();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["establishmentId"] = this.establishmentId;
        if (Array.isArray(this.salesIds)) {
            data["salesIds"] = [];
            for (let item of this.salesIds)
                data["salesIds"].push(item);
        }
        data["timePeriod"] = this.timePeriod ? this.timePeriod.toJSON() : <any>undefined;
        data["timeResolution"] = this.timeResolution;
        data["upperLag"] = this.upperLag;
        data["lowerLag"] = this.lowerLag;
        super.toJSON(data);
        return data;
    }
}

export interface ICorrelationCommand extends ICommandBase {
    establishmentId: string;
    salesIds: string[];
    timePeriod: DateTimePeriod;
    timeResolution: TimeResolution;
    upperLag: number;
    lowerLag: number;
}

export class DateTimePeriod implements IDateTimePeriod {
    start!: Date;
    end!: Date;

    constructor(data?: IDateTimePeriod) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.start = _data["start"] ? new Date(_data["start"].toString()) : <any>undefined;
            this.end = _data["end"] ? new Date(_data["end"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): DateTimePeriod {
        data = typeof data === 'object' ? data : {};
        let result = new DateTimePeriod();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["start"] = this.start ? this.start.toISOString() : <any>undefined;
        data["end"] = this.end ? this.end.toISOString() : <any>undefined;
        return data;
    }
}

export interface IDateTimePeriod {
    start: Date;
    end: Date;
}

export enum TimeResolution {
    Hour = 0,
    Date = 1,
    Month = 2,
    Year = 3,
}

export class ClusteringReturn extends ReturnBase implements IClusteringReturn {
    clusters!: string[][];
    calculationValues!: ValueTupleOfGuidAndListOfDouble[];

    constructor(data?: IClusteringReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["clusters"])) {
                this.clusters = [] as any;
                for (let item of _data["clusters"])
                    this.clusters!.push(item);
            }
            if (Array.isArray(_data["calculationValues"])) {
                this.calculationValues = [] as any;
                for (let item of _data["calculationValues"])
                    this.calculationValues!.push(ValueTupleOfGuidAndListOfDouble.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): ClusteringReturn {
        data = typeof data === 'object' ? data : {};
        let result = new ClusteringReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.clusters)) {
            data["clusters"] = [];
            for (let item of this.clusters)
                data["clusters"].push(item);
        }
        if (Array.isArray(this.calculationValues)) {
            data["calculationValues"] = [];
            for (let item of this.calculationValues)
                data["calculationValues"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IClusteringReturn extends IReturnBase {
    clusters: string[][];
    calculationValues: ValueTupleOfGuidAndListOfDouble[];
}

export class ValueTupleOfGuidAndListOfDouble implements IValueTupleOfGuidAndListOfDouble {
    item1!: string;
    item2!: number[] | undefined;

    constructor(data?: IValueTupleOfGuidAndListOfDouble) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item1 = _data["item1"];
            if (Array.isArray(_data["item2"])) {
                this.item2 = [] as any;
                for (let item of _data["item2"])
                    this.item2!.push(item);
            }
        }
    }

    static fromJS(data: any): ValueTupleOfGuidAndListOfDouble {
        data = typeof data === 'object' ? data : {};
        let result = new ValueTupleOfGuidAndListOfDouble();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item1"] = this.item1;
        if (Array.isArray(this.item2)) {
            data["item2"] = [];
            for (let item of this.item2)
                data["item2"].push(item);
        }
        return data;
    }
}

export interface IValueTupleOfGuidAndListOfDouble {
    item1: string;
    item2: number[] | undefined;
}

export abstract class ClusteringCommand extends CommandBase implements IClusteringCommand {
    establishmentId!: string;
    salesIds!: string[];

    protected _discriminator: string;

    constructor(data?: IClusteringCommand) {
        super(data);
        this._discriminator = "ClusteringCommand";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.establishmentId = _data["establishmentId"];
            if (Array.isArray(_data["salesIds"])) {
                this.salesIds = [] as any;
                for (let item of _data["salesIds"])
                    this.salesIds!.push(item);
            }
        }
    }

    static override fromJS(data: any): ClusteringCommand {
        data = typeof data === 'object' ? data : {};
        if (data["$type"] === "Clustering_TimeOfVisit_TotalPrice_Command") {
            let result = new Clustering_TimeOfVisit_TotalPrice_Command();
            result.init(data);
            return result;
        }
        if (data["$type"] === "Clustering_TimeOfVisit_LengthOfVisit_Command") {
            let result = new Clustering_TimeOfVisit_LengthOfVisit_Command();
            result.init(data);
            return result;
        }
        throw new Error("The abstract class 'ClusteringCommand' cannot be instantiated.");
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["$type"] = this._discriminator;
        data["establishmentId"] = this.establishmentId;
        if (Array.isArray(this.salesIds)) {
            data["salesIds"] = [];
            for (let item of this.salesIds)
                data["salesIds"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IClusteringCommand extends ICommandBase {
    establishmentId: string;
    salesIds: string[];
}

export class Clustering_TimeOfVisit_TotalPrice_Command extends ClusteringCommand implements IClustering_TimeOfVisit_TotalPrice_Command {
    bandwidthTimeOfVisit!: number;
    bandwidthTotalPrice!: number;

    constructor(data?: IClustering_TimeOfVisit_TotalPrice_Command) {
        super(data);
        this._discriminator = "Clustering_TimeOfVisit_TotalPrice_Command";
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.bandwidthTimeOfVisit = _data["bandwidthTimeOfVisit"];
            this.bandwidthTotalPrice = _data["bandwidthTotalPrice"];
        }
    }

    static override fromJS(data: any): Clustering_TimeOfVisit_TotalPrice_Command {
        data = typeof data === 'object' ? data : {};
        let result = new Clustering_TimeOfVisit_TotalPrice_Command();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["bandwidthTimeOfVisit"] = this.bandwidthTimeOfVisit;
        data["bandwidthTotalPrice"] = this.bandwidthTotalPrice;
        super.toJSON(data);
        return data;
    }
}

export interface IClustering_TimeOfVisit_TotalPrice_Command extends IClusteringCommand {
    bandwidthTimeOfVisit: number;
    bandwidthTotalPrice: number;
}

export class Clustering_TimeOfVisit_LengthOfVisit_Command extends ClusteringCommand implements IClustering_TimeOfVisit_LengthOfVisit_Command {

    constructor(data?: IClustering_TimeOfVisit_LengthOfVisit_Command) {
        super(data);
        this._discriminator = "Clustering_TimeOfVisit_LengthOfVisit_Command";
    }

    override init(_data?: any) {
        super.init(_data);
    }

    static override fromJS(data: any): Clustering_TimeOfVisit_LengthOfVisit_Command {
        data = typeof data === 'object' ? data : {};
        let result = new Clustering_TimeOfVisit_LengthOfVisit_Command();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        super.toJSON(data);
        return data;
    }
}

export interface IClustering_TimeOfVisit_LengthOfVisit_Command extends IClusteringCommand {
}

export class LoginCommand implements ILoginCommand {
    username!: string;
    password!: string;

    constructor(data?: ILoginCommand) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.username = _data["username"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginCommand {
        data = typeof data === 'object' ? data : {};
        let result = new LoginCommand();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginCommand {
    username: string;
    password: string;
}

export class GetEstablishmentsIdReturn extends ReturnBase implements IGetEstablishmentsIdReturn {
    ids!: string[];

    constructor(data?: IGetEstablishmentsIdReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["ids"])) {
                this.ids = [] as any;
                for (let item of _data["ids"])
                    this.ids!.push(item);
            }
        }
    }

    static override fromJS(data: any): GetEstablishmentsIdReturn {
        data = typeof data === 'object' ? data : {};
        let result = new GetEstablishmentsIdReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.ids)) {
            data["ids"] = [];
            for (let item of this.ids)
                data["ids"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetEstablishmentsIdReturn extends IReturnBase {
    ids: string[];
}

export class GetEstablishmentsCommand extends CommandBase implements IGetEstablishmentsCommand {
    establishmentIds!: string[];

    constructor(data?: IGetEstablishmentsCommand) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["establishmentIds"])) {
                this.establishmentIds = [] as any;
                for (let item of _data["establishmentIds"])
                    this.establishmentIds!.push(item);
            }
        }
    }

    static override fromJS(data: any): GetEstablishmentsCommand {
        data = typeof data === 'object' ? data : {};
        let result = new GetEstablishmentsCommand();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.establishmentIds)) {
            data["establishmentIds"] = [];
            for (let item of this.establishmentIds)
                data["establishmentIds"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetEstablishmentsCommand extends ICommandBase {
    establishmentIds: string[];
}

export class GetEstablishmentsDTOReturn extends ReturnBase implements IGetEstablishmentsDTOReturn {
    dtos!: EstablishmentDTO[];

    constructor(data?: IGetEstablishmentsDTOReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["dtos"])) {
                this.dtos = [] as any;
                for (let item of _data["dtos"])
                    this.dtos!.push(EstablishmentDTO.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): GetEstablishmentsDTOReturn {
        data = typeof data === 'object' ? data : {};
        let result = new GetEstablishmentsDTOReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.dtos)) {
            data["dtos"] = [];
            for (let item of this.dtos)
                data["dtos"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetEstablishmentsDTOReturn extends IReturnBase {
    dtos: EstablishmentDTO[];
}

export class EstablishmentDTO implements IEstablishmentDTO {
    id!: string;
    name!: string;
    items!: string[];
    tables!: string[];
    sales!: string[];

    constructor(data?: IEstablishmentDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(item);
            }
            if (Array.isArray(_data["tables"])) {
                this.tables = [] as any;
                for (let item of _data["tables"])
                    this.tables!.push(item);
            }
            if (Array.isArray(_data["sales"])) {
                this.sales = [] as any;
                for (let item of _data["sales"])
                    this.sales!.push(item);
            }
        }
    }

    static fromJS(data: any): EstablishmentDTO {
        data = typeof data === 'object' ? data : {};
        let result = new EstablishmentDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item);
        }
        if (Array.isArray(this.tables)) {
            data["tables"] = [];
            for (let item of this.tables)
                data["tables"].push(item);
        }
        if (Array.isArray(this.sales)) {
            data["sales"] = [];
            for (let item of this.sales)
                data["sales"].push(item);
        }
        return data;
    }
}

export interface IEstablishmentDTO {
    id: string;
    name: string;
    items: string[];
    tables: string[];
    sales: string[];
}

export class GetItemsIdReturn extends ReturnBase implements IGetItemsIdReturn {
    id!: string[];

    constructor(data?: IGetItemsIdReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["id"])) {
                this.id = [] as any;
                for (let item of _data["id"])
                    this.id!.push(item);
            }
        }
    }

    static override fromJS(data: any): GetItemsIdReturn {
        data = typeof data === 'object' ? data : {};
        let result = new GetItemsIdReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.id)) {
            data["id"] = [];
            for (let item of this.id)
                data["id"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetItemsIdReturn extends IReturnBase {
    id: string[];
}

export class GetItemsCommand extends CommandBase implements IGetItemsCommand {
    establishmentId!: string;
    itemIds!: string[];

    constructor(data?: IGetItemsCommand) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.establishmentId = _data["establishmentId"];
            if (Array.isArray(_data["itemIds"])) {
                this.itemIds = [] as any;
                for (let item of _data["itemIds"])
                    this.itemIds!.push(item);
            }
        }
    }

    static override fromJS(data: any): GetItemsCommand {
        data = typeof data === 'object' ? data : {};
        let result = new GetItemsCommand();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["establishmentId"] = this.establishmentId;
        if (Array.isArray(this.itemIds)) {
            data["itemIds"] = [];
            for (let item of this.itemIds)
                data["itemIds"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetItemsCommand extends ICommandBase {
    establishmentId: string;
    itemIds: string[];
}

export class GetItemsDTOReturn extends ReturnBase implements IGetItemsDTOReturn {
    dto!: ItemDTO[];

    constructor(data?: IGetItemsDTOReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["dto"])) {
                this.dto = [] as any;
                for (let item of _data["dto"])
                    this.dto!.push(ItemDTO.fromJS(item));
            }
        }
    }

    static override fromJS(data: any): GetItemsDTOReturn {
        data = typeof data === 'object' ? data : {};
        let result = new GetItemsDTOReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.dto)) {
            data["dto"] = [];
            for (let item of this.dto)
                data["dto"].push(item.toJSON());
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetItemsDTOReturn extends IReturnBase {
    dto: ItemDTO[];
}

export class ItemDTO implements IItemDTO {
    id!: string;
    name!: string;
    price!: number;

    constructor(data?: IItemDTO) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.price = _data["price"];
        }
    }

    static fromJS(data: any): ItemDTO {
        data = typeof data === 'object' ? data : {};
        let result = new ItemDTO();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["price"] = this.price;
        return data;
    }
}

export interface IItemDTO {
    id: string;
    name: string;
    price: number;
}

export class GetSalesReturn extends ReturnBase implements IGetSalesReturn {
    sales!: string[];

    constructor(data?: IGetSalesReturn) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["sales"])) {
                this.sales = [] as any;
                for (let item of _data["sales"])
                    this.sales!.push(item);
            }
        }
    }

    static override fromJS(data: any): GetSalesReturn {
        data = typeof data === 'object' ? data : {};
        let result = new GetSalesReturn();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.sales)) {
            data["sales"] = [];
            for (let item of this.sales)
                data["sales"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

export interface IGetSalesReturn extends IReturnBase {
    sales: string[];
}

export class GetSalesCommand extends CommandBase implements IGetSalesCommand {
    establishmentId!: string;
    salesIds!: string[];
    salesSorting!: SalesSorting | undefined;

    constructor(data?: IGetSalesCommand) {
        super(data);
    }

    override init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.establishmentId = _data["establishmentId"];
            if (Array.isArray(_data["salesIds"])) {
                this.salesIds = [] as any;
                for (let item of _data["salesIds"])
                    this.salesIds!.push(item);
            }
            this.salesSorting = _data["salesSorting"] ? SalesSorting.fromJS(_data["salesSorting"]) : <any>undefined;
        }
    }

    static override fromJS(data: any): GetSalesCommand {
        data = typeof data === 'object' ? data : {};
        let result = new GetSalesCommand();
        result.init(data);
        return result;
    }

    override toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["establishmentId"] = this.establishmentId;
        if (Array.isArray(this.salesIds)) {
            data["salesIds"] = [];
            for (let item of this.salesIds)
                data["salesIds"].push(item);
        }
        data["salesSorting"] = this.salesSorting ? this.salesSorting.toJSON() : <any>undefined;
        super.toJSON(data);
        return data;
    }
}

export interface IGetSalesCommand extends ICommandBase {
    establishmentId: string;
    salesIds: string[];
    salesSorting: SalesSorting | undefined;
}

export class SalesSorting implements ISalesSorting {
    any!: string[] | undefined;
    excatly!: string[] | undefined;
    all!: string[] | undefined;
    withinTimeperiods!: ValueTupleOfDateTimeAndDateTime[] | undefined;
    mustContainAllAttributes!: SaleAttributes[] | undefined;

    constructor(data?: ISalesSorting) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["any"])) {
                this.any = [] as any;
                for (let item of _data["any"])
                    this.any!.push(item);
            }
            if (Array.isArray(_data["excatly"])) {
                this.excatly = [] as any;
                for (let item of _data["excatly"])
                    this.excatly!.push(item);
            }
            if (Array.isArray(_data["all"])) {
                this.all = [] as any;
                for (let item of _data["all"])
                    this.all!.push(item);
            }
            if (Array.isArray(_data["withinTimeperiods"])) {
                this.withinTimeperiods = [] as any;
                for (let item of _data["withinTimeperiods"])
                    this.withinTimeperiods!.push(ValueTupleOfDateTimeAndDateTime.fromJS(item));
            }
            if (Array.isArray(_data["mustContainAllAttributes"])) {
                this.mustContainAllAttributes = [] as any;
                for (let item of _data["mustContainAllAttributes"])
                    this.mustContainAllAttributes!.push(item);
            }
        }
    }

    static fromJS(data: any): SalesSorting {
        data = typeof data === 'object' ? data : {};
        let result = new SalesSorting();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.any)) {
            data["any"] = [];
            for (let item of this.any)
                data["any"].push(item);
        }
        if (Array.isArray(this.excatly)) {
            data["excatly"] = [];
            for (let item of this.excatly)
                data["excatly"].push(item);
        }
        if (Array.isArray(this.all)) {
            data["all"] = [];
            for (let item of this.all)
                data["all"].push(item);
        }
        if (Array.isArray(this.withinTimeperiods)) {
            data["withinTimeperiods"] = [];
            for (let item of this.withinTimeperiods)
                data["withinTimeperiods"].push(item.toJSON());
        }
        if (Array.isArray(this.mustContainAllAttributes)) {
            data["mustContainAllAttributes"] = [];
            for (let item of this.mustContainAllAttributes)
                data["mustContainAllAttributes"].push(item);
        }
        return data;
    }
}

export interface ISalesSorting {
    any: string[] | undefined;
    excatly: string[] | undefined;
    all: string[] | undefined;
    withinTimeperiods: ValueTupleOfDateTimeAndDateTime[] | undefined;
    mustContainAllAttributes: SaleAttributes[] | undefined;
}

export class ValueTupleOfDateTimeAndDateTime implements IValueTupleOfDateTimeAndDateTime {
    item1!: Date;
    item2!: Date;

    constructor(data?: IValueTupleOfDateTimeAndDateTime) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.item1 = _data["item1"] ? new Date(_data["item1"].toString()) : <any>undefined;
            this.item2 = _data["item2"] ? new Date(_data["item2"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): ValueTupleOfDateTimeAndDateTime {
        data = typeof data === 'object' ? data : {};
        let result = new ValueTupleOfDateTimeAndDateTime();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["item1"] = this.item1 ? this.item1.toISOString() : <any>undefined;
        data["item2"] = this.item2 ? this.item2.toISOString() : <any>undefined;
        return data;
    }
}

export interface IValueTupleOfDateTimeAndDateTime {
    item1: Date;
    item2: Date;
}

export enum SaleAttributes {
    Table = 0,
    Items = 1,
    TimestampArrival = 2,
    TimestampPayment = 3,
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}