# Use root/example as user/password credentials
version: '3.1'

services:

  # db:
  #   image: mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   # command: --default-authentication-plugin=mysql_native_password
  #   volumes:
  #   - "./.data/db:/var/lib/mysql"
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mydb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #   ports:
  #     - 3306:3306
  #     - 33060:33060

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   data: